stages:
  - verify

default:
  image: node:22.12.0
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.14.2 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pnpm-store
      - node_modules/

lint:
  stage: verify
  script:
    - pnpm lint

build:
  stage: verify
  script:
    - pnpm build
